### ISSUE TITLE
能整一个macOS版本吗

### ISSUE THREAD

**Issue by cddehsy** [smloli/AlizipShare#4]
能整一个macOS版本吗

**Comment by smloli** [comment]
这软件已经失效了

**Comment by dairui2** [comment]
> 这软件已经失效了

那有什么软件可以代替它转换已经存在的mp4文件呢

**Comment by smloli** [comment]
> > 这软件已经失效了
> 
> 那有什么软件可以代替它转换已经存在的mp4文件呢

https://github.com/rippod/apate
